package com.isea533.mybatis.mapper;

import com.isea533.mybatis.model.Country2;
import com.isea533.mybatis.model.Country2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Country2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    int countByExample(Country2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    int deleteByExample(Country2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    int insert(Country2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    int insertSelective(Country2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    List<Country2> selectByExample(Country2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    Country2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    int updateByExampleSelective(@Param("record") Country2 record, @Param("example") Country2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    int updateByExample(@Param("record") Country2 record, @Param("example") Country2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    int updateByPrimaryKeySelective(Country2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    int updateByPrimaryKey(Country2 record);
}