package com.isea533.mybatis.mapper;

import com.github.abel533.mapper.Mapper;
import com.isea533.mybatis.model.Country2;
import com.isea533.mybatis.model.Country2Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface Country2Mapper extends Mapper<Country2> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    int countByExample(Country2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    int deleteByExample(Country2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    List<Country2> selectByExample(Country2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    int updateByExampleSelective(@Param("record") Country2 record, @Param("example") Country2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Mon Dec 08 11:25:39 CST 2014
     */
    int updateByExample(@Param("record") Country2 record, @Param("example") Country2Example example);
}